export const ENCRYPTION_ALGORITHM = "aes-256-gcm";
export const KEY = "dfwa145fg5093$521";
export const IV = Buffer.from("dzvfd#42q2251@3564!");
export const AUTOMATIC_NOTIFICATIONS_QUEUE = 'automatic-notifications';
export const NOTIFICATIONS_PROCESS = 'SENDING_AUTOMATIC_EMAIL_NOTIFICATIONS';
export const NOTIFICATIONS_PROCESS_SMS = "SENDING_AUTOMATIC_SMS_NOTIFICATIONS";
export const NOTIFICATIONS_PROCESS_PUSH = "SENDING_AUTOMATIC_PUSH_NOTIFICATIONS";

